name: Avalonia .NET 6 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        submodules: recursive 

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish ./LemonManager/LemonManager.csproj -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -c Release --self-contained

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-artifacts
        path: ./LemonManager/bin/Release/net6.0/
