name: Avalonia .NET 6 Build on Windows

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main

jobs:
 build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: avalonia-app-build
        path: ./bin/Release/net6.0/
